[package]
name = "shuftlib"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.75"
num-rational = "0.4.1"
rand="0.8"
strum = {version="0.25", features=["derive"]}

[dev-dependencies]
